# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Voices' do
    
    pod "AFNetworking", "~> 2.0"
    pod "Shimmer"
    pod 'STPopup'
    pod 'SSZipArchive'
    pod 'Google/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Google/CloudMessaging'

end

target 'VoicesTests' do
    
end

